apiVersion: v1
kind: Service
metadata:
  name: python-django-app-nodeport-service
spec:
  type: NodePort
  selector:
    app: django-app
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30007
